"""Gate-5 Monte Carlo orchestration for the residential demand model."""

from .aggregation import (
    aggregate_stock_results,
    load_stock_weights,
    stock_distribution_summary,
    stock_contribution_summary,
    validate_stock_weights,
)
from .contracts import (
    MODEL_CONTRACT_VERSION,
    ModelScenario,
    MonteCarloContractError,
    MonteCarloDiagnostics,
    MonteCarloResult,
    RunSpec,
    WeatherMember,
    archetype_state_sha256,
    diagnostics_to_record,
)
from .design import (
    ConvergenceRule,
    PROSPECTIVE_N160_CONVERGENCE_RULE,
    PROSPECTIVE_N320_N640_CONVERGENCE_RULE,
    build_balanced_manifest,
    distribution_summary,
    evaluate_seed_convergence,
    make_seed_bank,
    ordered_seed_bank_sha256,
    paired_model_scenario_deltas,
    paired_renovation_deltas,
    variance_contributions,
)
from .interface import simulate
from .convergence_runner import (
    ConvergenceSelection,
    convergence_status,
    load_convergence_panel,
    load_convergence_selection,
    prepare_convergence_experiment,
    run_convergence_experiment,
)
from .convergence_extension import (
    CONVERGENCE_EXTENSION_CONTRACT_VERSION,
    DEFAULT_CONVERGENCE_EXTENSION_OUTPUT_DIR,
    convergence_extension_status,
    load_convergence_extension_selection,
    prepare_convergence_extension,
    run_convergence_extension,
)
from .convergence_continuation import (
    CONVERGENCE_CONTINUATION_CONTRACT_VERSION,
    CONTINUATION_CHECKPOINTS,
    DEFAULT_CONVERGENCE_CONTINUATION_OUTPUT_DIR,
    convergence_continuation_status,
    load_convergence_continuation_selection,
    prepare_convergence_continuation,
    run_convergence_continuation,
)
from .runner import execute_streaming_stock_design, streaming_stock_status
from .postprocess import (
    POSTPROCESS_CONTRACT_VERSION,
    postprocess_production_results,
    postprocessing_status,
)
from .reporting import (
    DEFAULT_FIGURE_DIR,
    FIGURE_BASENAMES,
    FIGURE_PROVENANCE_FILENAME,
    REPORTING_CONTRACT_VERSION,
    REPORTING_SUMMARY_FILENAME,
    authenticate_reporting_inputs,
    generate_production_report,
    reporting_status,
)
from .sensitivity import (
    STRUCTURAL_SENSITIVITY_CONTRACT_VERSION,
    STRUCTURAL_SENSITIVITY_SUMMARY_VERSION,
    default_structural_sensitivity_output_dir,
    evaluate_structural_sensitivity_screen,
    prepare_structural_sensitivity_screen,
    run_structural_sensitivity_screen,
    structural_sensitivity_status,
)
from .scenarios import (
    MODEL_SCENARIOS,
    resolve_model_scenario,
    scenario_catalog,
)
from .weather import (
    forcing_sha256,
    load_weather_catalog,
    load_weather_member,
    load_weather_members,
)
from .stock_streaming import StreamingStockAccumulator

__all__ = [
    "MODEL_CONTRACT_VERSION",
    "MODEL_SCENARIOS",
    "ConvergenceRule",
    "ConvergenceSelection",
    "CONVERGENCE_EXTENSION_CONTRACT_VERSION",
    "CONVERGENCE_CONTINUATION_CONTRACT_VERSION",
    "CONTINUATION_CHECKPOINTS",
    "DEFAULT_CONVERGENCE_CONTINUATION_OUTPUT_DIR",
    "DEFAULT_CONVERGENCE_EXTENSION_OUTPUT_DIR",
    "DEFAULT_FIGURE_DIR",
    "FIGURE_BASENAMES",
    "PROSPECTIVE_N160_CONVERGENCE_RULE",
    "PROSPECTIVE_N320_N640_CONVERGENCE_RULE",
    "POSTPROCESS_CONTRACT_VERSION",
    "FIGURE_PROVENANCE_FILENAME",
    "REPORTING_CONTRACT_VERSION",
    "REPORTING_SUMMARY_FILENAME",
    "STRUCTURAL_SENSITIVITY_CONTRACT_VERSION",
    "STRUCTURAL_SENSITIVITY_SUMMARY_VERSION",
    "ModelScenario",
    "MonteCarloContractError",
    "MonteCarloDiagnostics",
    "MonteCarloResult",
    "RunSpec",
    "WeatherMember",
    "StreamingStockAccumulator",
    "aggregate_stock_results",
    "authenticate_reporting_inputs",
    "archetype_state_sha256",
    "build_balanced_manifest",
    "convergence_status",
    "convergence_extension_status",
    "convergence_continuation_status",
    "diagnostics_to_record",
    "default_structural_sensitivity_output_dir",
    "distribution_summary",
    "evaluate_seed_convergence",
    "evaluate_structural_sensitivity_screen",
    "execute_streaming_stock_design",
    "forcing_sha256",
    "generate_production_report",
    "load_stock_weights",
    "load_convergence_panel",
    "load_convergence_extension_selection",
    "load_convergence_continuation_selection",
    "load_convergence_selection",
    "load_weather_catalog",
    "load_weather_member",
    "load_weather_members",
    "make_seed_bank",
    "ordered_seed_bank_sha256",
    "paired_model_scenario_deltas",
    "paired_renovation_deltas",
    "postprocess_production_results",
    "postprocessing_status",
    "prepare_convergence_experiment",
    "prepare_convergence_extension",
    "prepare_convergence_continuation",
    "prepare_structural_sensitivity_screen",
    "resolve_model_scenario",
    "reporting_status",
    "run_convergence_experiment",
    "run_convergence_extension",
    "run_convergence_continuation",
    "run_structural_sensitivity_screen",
    "scenario_catalog",
    "simulate",
    "stock_contribution_summary",
    "stock_distribution_summary",
    "streaming_stock_status",
    "structural_sensitivity_status",
    "validate_stock_weights",
    "variance_contributions",
]
