"""
Generate a LaTeX table of the base (unweighted) physical archetype matrix.

Reads BE_building_stock/data/matrices/national/base_physical_archetype_matrix.csv,
drops the `archetype_id` and `TABULA_type_number` columns as requested, and
writes a landscape `longtable` with short column codes plus a legend, to
../tables/base_physical_archetype_matrix.tex.
"""

from pathlib import Path
import csv

ROOT = Path(__file__).resolve().parent.parent
SRC = (ROOT / "BE_building_stock" / "data" / "matrices" / "national"
       / "base_physical_archetype_matrix.csv")
OUT = ROOT / "tables"
OUT.mkdir(exist_ok=True)

DROP = {"archetype_id", "TABULA_type_number"}

# CSV column -> (short header code, legend description)
CODES = {
    "dwelling_type": ("Type", "Dwelling type"),
    "construction_period": ("Period", "Construction period"),
    "floor_surface_area_m2": (r"$A_\text{fl}$", r"Floor surface area (m$^2$)"),
    "protected_volume_m3": (r"$V$", r"Protected volume (m$^3$)"),
    "total_building_envelope_area_m2": (r"$A_\text{env}$", r"Total envelope area (m$^2$)"),
    "roof_area_m2": (r"$A_\text{roof}$", r"Roof area (m$^2$)"),
    "exterior_wall_area_m2": (r"$A_\text{wall}$", r"Exterior wall area (m$^2$)"),
    "exterior_wall_bordering_unheated_neighboring_spaces_m2": (r"$A_\text{wall,u}$", r"Exterior wall bordering unheated spaces (m$^2$)"),
    "floor_on_soil_m2": (r"$A_\text{fl,soil}$", r"Floor on soil (m$^2$)"),
    "floor_bordering_unheated_neighboring_spaces_m2": (r"$A_\text{fl,u}$", r"Floor bordering unheated spaces (m$^2$)"),
    "doors_area_m2": (r"$A_\text{door}$", r"Door area (m$^2$)"),
    "windows_north_m2": (r"$W_\text{N}$", r"Windows, north (m$^2$)"),
    "windows_east_m2": (r"$W_\text{E}$", r"Windows, east (m$^2$)"),
    "windows_south_m2": (r"$W_\text{S}$", r"Windows, south (m$^2$)"),
    "windows_west_m2": (r"$W_\text{W}$", r"Windows, west (m$^2$)"),
    "windows_total_m2": (r"$W_\text{tot}$", r"Windows, total (m$^2$)"),
    "U_facade_W_m2K": (r"$U_\text{fac}$", r"Facade U-value (W/m$^2$K)"),
    "U_roof_W_m2K": (r"$U_\text{roof}$", r"Roof U-value (W/m$^2$K)"),
    "U_floor_W_m2K": (r"$U_\text{fl}$", r"Floor U-value (W/m$^2$K)"),
    "U_window_W_m2K": (r"$U_\text{win}$", r"Window U-value (W/m$^2$K)"),
    "U_door_W_m2K": (r"$U_\text{door}$", r"Door U-value (W/m$^2$K)"),
    "v50_m3_h_m2": (r"$v_{50}$", r"Air permeability at 50\,Pa (m$^3$/(h$\cdot$m$^2$))"),
}


def esc(s: str) -> str:
    return s.replace("&", r"\&").replace("%", r"\%")


with open(SRC, newline="") as f:
    reader = csv.DictReader(f)
    cols = [c for c in reader.fieldnames if c not in DROP]
    rows = list(reader)

headers = [CODES[c][0] for c in cols]
# left-align the two text columns, right-align the numeric ones
align = "ll" + "r" * (len(cols) - 2)

lines = []
lines.append("% Auto-generated by scripts/make_archetype_table.py -- do not edit by hand.")
lines.append(r"% Requires: \usepackage{longtable, booktabs, pdflscape, amsmath}")
lines.append(r"\begin{landscape}")
lines.append(r"\footnotesize")
lines.append(r"\setlength{\tabcolsep}{3pt}")
lines.append(r"\begin{longtable}{" + align + "}")
lines.append(r"\caption{Base (unweighted) physical archetype matrix: representative "
             r"geometry, envelope U-values and air-permeability for the 25 Belgian "
             r"TABULA/VITO dwelling-unit types~\cite{tabula_be_vito}. "
             r"Column codes are defined below the table.}"
             r"\label{tab:base_physical_archetype_matrix}\\")
lines.append(r"\toprule")
lines.append(" & ".join(headers) + r" \\")
lines.append(r"\midrule")
lines.append(r"\endfirsthead")
lines.append(r"\multicolumn{%d}{c}{\tablename\ \thetable\ -- continued} \\" % len(cols))
lines.append(r"\toprule")
lines.append(" & ".join(headers) + r" \\")
lines.append(r"\midrule")
lines.append(r"\endhead")
lines.append(r"\midrule \multicolumn{%d}{r}{\textit{continued on next page}} \\" % len(cols))
lines.append(r"\endfoot")
lines.append(r"\bottomrule")
lines.append(r"\endlastfoot")

for row in rows:
    cells = [esc(row[c]) for c in cols]
    lines.append(" & ".join(cells) + r" \\")

lines.append(r"\end{longtable}")
lines.append(r"\end{landscape}")
lines.append("")
lines.append(r"\noindent\footnotesize\textbf{Column codes.} " +
             "; ".join(f"{CODES[c][0]}: {CODES[c][1]}" for c in cols) + ".")

(OUT / "base_physical_archetype_matrix.tex").write_text("\n".join(lines) + "\n")
print("Wrote", OUT / "base_physical_archetype_matrix.tex", f"({len(rows)} rows, {len(cols)} cols)")
