"""Generate the appendix table of 75 unique physical archetype--state cells."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
BASE_SOURCE = (
    ROOT
    / "BE_building_stock"
    / "data"
    / "matrices"
    / "national"
    / "base_physical_archetype_matrix.csv"
)
STATE_SOURCE = (
    ROOT
    / "BE_building_stock"
    / "data"
    / "scenarios"
    / "renovation"
    / "archetype_matrix_2050_renovation_scenarios.csv"
)
OUTPUT = ROOT / "tables" / "physical_archetype_state_matrix.tex"

STATE_ORDER = {
    "TABULA_existing": 0,
    "TABULA_standard_B_proxy": 1,
    "TABULA_advanced_A_proxy": 2,
}
STATE_LABELS = {
    "TABULA_existing": "Existing",
    "TABULA_standard_B_proxy": "Standard/B",
    "TABULA_advanced_A_proxy": "Advanced/A",
}
VENTILATION_LABELS = {
    "existing_unspecified": "Existing",
    "exhaust_air_ventilation": "Exhaust air",
    "balanced_mechanical_HRV": "Balanced HRV",
}
PHYSICAL_COLUMNS = (
    "U_facade_W_m2K",
    "U_roof_W_m2K",
    "U_floor_W_m2K",
    "U_window_W_m2K",
    "U_door_W_m2K",
    "v50_m3_h_m2",
    "infiltration_ach_normal_h_1",
    "ventilation_system",
    "hrv_eta",
    "summer_bypass",
)


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def escape(value: str) -> str:
    return value.replace("&", r"\&").replace("%", r"\%")


base_rows = read_rows(BASE_SOURCE)
if len(base_rows) != 25:
    raise RuntimeError(f"Expected 25 base archetypes; found {len(base_rows)}.")
base_by_id = {row["archetype_id"]: row for row in base_rows}
if len(base_by_id) != 25:
    raise RuntimeError("Base archetype IDs are not unique.")

regional_rows = [
    row
    for row in read_rows(STATE_SOURCE)
    if row["scenario"] == "central" and row["target_year"] == "2050"
]
grouped: dict[tuple[str, str], list[dict[str, str]]] = {}
for row in regional_rows:
    grouped.setdefault((row["archetype_id"], row["state_id"]), []).append(row)
if len(grouped) != 75:
    raise RuntimeError(f"Expected 75 physical archetype--state keys; found {len(grouped)}.")

unique_rows: list[dict[str, str]] = []
for (archetype_id, state_id), copies in grouped.items():
    if len(copies) != 3:
        raise RuntimeError(
            f"Expected three regional copies for {archetype_id}/{state_id}; "
            f"found {len(copies)}."
        )
    for column in PHYSICAL_COLUMNS:
        if len({row[column] for row in copies}) != 1:
            raise RuntimeError(
                f"Regional copies disagree for {archetype_id}/{state_id}/{column}."
            )
    base = base_by_id[archetype_id]
    unique_rows.append(
        {
            **copies[0],
            "TABULA_type_number": base["TABULA_type_number"],
            "floor_surface_area_m2": base["floor_surface_area_m2"],
        }
    )

unique_rows.sort(
    key=lambda row: (
        int(row["TABULA_type_number"]),
        STATE_ORDER[row["state_id"]],
    )
)

column_count = 15
lines = [
    "% Auto-generated by scripts/make_archetype_state_table.py -- do not edit by hand.",
    r"% Requires: \usepackage{longtable, booktabs, pdflscape, amsmath}",
    r"\scriptsize",
    r"\setlength{\tabcolsep}{2.5pt}",
    r"\begin{longtable}{rlllr*{7}{r}lrc}",
    (
        r"\caption{Unique physical archetype--state matrix used in the thermal "
        r"simulations: 25 Belgian TABULA/VITO dwelling archetypes in three physical "
        r"states, giving 75 cells~\cite{tabula_be_vito}.}"
        r"\label{tab:appendix_physical_archetype_state_matrix}\\"
    ),
    r"\toprule",
    (
        r"No. & Type & Period & State & $A_f$ & $U_{fac}$ & $U_{roof}$ & $U_{fl}$ "
        r"& $U_{win}$ & $U_{door}$ & $v_{50}$ & $n_{inf}$ & Ventilation "
        r"& $\eta_{HRV}$ & Bypass \\"
    ),
    r"\midrule",
    r"\endfirsthead",
    rf"\multicolumn{{{column_count}}}{{c}}{{\tablename\ \thetable\ -- continued}} \\",
    r"\toprule",
    (
        r"No. & Type & Period & State & $A_f$ & $U_{fac}$ & $U_{roof}$ & $U_{fl}$ "
        r"& $U_{win}$ & $U_{door}$ & $v_{50}$ & $n_{inf}$ & Ventilation "
        r"& $\eta_{HRV}$ & Bypass \\"
    ),
    r"\midrule",
    r"\endhead",
    rf"\midrule \multicolumn{{{column_count}}}{{r}}{{\textit{{continued on next page}}}} \\",
    r"\endfoot",
    r"\bottomrule",
    r"\endlastfoot",
]

for row in unique_rows:
    hrv = "--" if row["hrv_eta"] == "" else f'{float(row["hrv_eta"]):.1f}'
    bypass = {"": "--", "True": "Yes", "False": "No"}[row["summer_bypass"]]
    cells = (
        str(int(row["TABULA_type_number"])),
        escape(row["dwelling_type"]),
        escape(row["construction_period"]),
        STATE_LABELS[row["state_id"]],
        f'{float(row["floor_surface_area_m2"]):.1f}',
        f'{float(row["U_facade_W_m2K"]):.2f}',
        f'{float(row["U_roof_W_m2K"]):.2f}',
        f'{float(row["U_floor_W_m2K"]):.2f}',
        f'{float(row["U_window_W_m2K"]):.2f}',
        f'{float(row["U_door_W_m2K"]):.2f}',
        f'{float(row["v50_m3_h_m2"]):.2f}',
        f'{float(row["infiltration_ach_normal_h_1"]):.3f}',
        VENTILATION_LABELS[row["ventilation_system"]],
        hrv,
        bypass,
    )
    lines.append(" & ".join(cells) + r" \\")

lines.extend(
    [
        r"\end{longtable}",
        r"\noindent\scriptsize\textbf{Column codes.} "
        r"$A_f$: conditioned floor area (m$^2$); "
        r"$U_{fac}$, $U_{roof}$, $U_{fl}$, $U_{win}$ and $U_{door}$: component "
        r"U-values (W/(m$^2$K)); $v_{50}$: air permeability at 50~Pa "
        r"(m$^3$/(h$\cdot$m$^2$)); $n_{inf}$: normal-pressure infiltration "
        r"air-change proxy (h$^{-1}$); $\eta_{HRV}$: nominal heat-recovery "
        r"efficiency. Existing, Standard/B and Advanced/A correspond to the "
        r"three physical states defined in \Cref{sec:method_building_stock}.",
    ]
)

OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Wrote {OUTPUT} ({len(unique_rows)} rows)")
